AWX:
  enabled: true
  name: awx
  spec:
    admin_user: admin
    service_type: ClusterIP

  postgres:
    enabled: false
    host: Unset
    port: 5678
    dbName: Unset
    username: admin
    password: Unset
    sslmode: prefer
    type: unmanaged

rbac:
  create: true

operator-controller: {}

operator-controller-containers: {}

ingress:
  enabled: true
  name: awx-ingress
  namespace: awx
  forceSslRedirect: "true"
  backendProtocol: HTTP
  rewriteTarget: /
  className: nginx
  host: awx.example.com
  path: /
  serviceName: awx-service
  servicePort: 80

