apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zoigeorgiou/awx-operator-deploy.git
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: awx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
