{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name | default "awx-ingress" }}
  namespace: {{ .Values.ingress.namespace | default "awx" }}
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "{{ .Values.ingress.forceSslRedirect | default "true" }}"
    nginx.ingress.kubernetes.io/backend-protocol: "{{ .Values.ingress.backendProtocol | default "HTTP" }}"
    nginx.ingress.kubernetes.io/rewrite-target: "{{ .Values.ingress.rewriteTarget | default "/" }}"
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
  - host: {{ .Values.ingress.host | default "awx.example.com" }}
    http:
      paths:
      - pathType: Prefix
        path: {{ .Values.ingress.path | default "/" }}
        backend:
          service:
            name: {{ .Values.ingress.serviceName | default "awx-service" }}
            port:
              number: {{ .Values.ingress.servicePort | default 80 }}
{{- end }}

